version: '3'

services:
  nginx:
    image: kirshov/ma-nginx
    volumes:
      - ./:/app
    container_name: s-nginx
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - service-1

  service-1:
    image: kirshov/service-1
    container_name: service-1
    volumes:
      - ./app:/app
      - ./app/var/cache:/app/var/cache
