ARG PHP_BASEIMAGE_VERSION=8.2
FROM php:${PHP_BASEIMAGE_VERSION}-fpm

RUN apt-get update && apt-get install -y \
    libpq-dev \
    wget \
    zlib1g-dev \
    libmcrypt-dev \
    libzip-dev \
    nano \
    zip

RUN docker-php-ext-install pdo pdo_pgsql

COPY ./app-billing /app-billing

WORKDIR /app-billing
