version: '3'

services:
  nginx:
    build:
      context: ./.docker/nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "81:81"
    depends_on:
      - users-service
      - app-auth

  users-service:
    build:
      context: ./.docker/users-service
    container_name: users-service
    volumes:
      - ./app:/app
      - ./app/config:/app/config
      - ./app/var/cache:/app/var/cache

  app-auth:
    build:
      context: ./.docker/app-auth
    container_name: app-auth
    environment:
      POSTGRES_HOST: 'service-postgres'
      POSTGRES_DB: 'users'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres_pass'
    volumes:
      - ./app-auth:/app-auth

  service-postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_HOST: 'postgres'
      POSTGRES_DB: 'users'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres_pass'
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    container_name: service-postgres

volumes:
  db-data:
