
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configMaps.appConfigMap }}
data:
  .env.local: |
    APP_ENV={{ .Values.app.env }}
    APP_SECRET={{ .Values.app.secret }}
    DATABASE_URL={{ .Values.app.dbUrl | quote }}
    BILLING_URL=http://service-billing:80
    NOTIFY_URL=http://service-notify:80

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configMaps.nginxConfigMap }}
data:
  app.conf: |
    server {
      listen 80;
      index index.php index.html;
      error_log /var/log/nginx/error.log;
      access_log /var/log/nginx/access.log;
      root /app/public;

      client_max_body_size 128m;

      location / {
        try_files $uri $uri/ /index.php?$args;
      }

      location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
      }
    }
