apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.migrationJob.name }}
  annotations:
    "helm.sh/hook": post-install
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.migrationJob.containerName | quote }}
          image: "{{ .Values.serviceMainApp.image }}:{{ .Values.serviceMainApp.tag }}"
          command:
            {{- range .Values.migrationJob.command }}
              - {{ . | quote}}
            {{ end }}
          volumeMounts:
            {{- toYaml .Values.migrationJob.volumeMounts | nindent 12 }}
      restartPolicy: {{ .Values.migrationJob.restartPolicy }}
      volumes:
        {{- toYaml .Values.migrationJob.volumes | nindent 8 }}
  backoffLimit: {{ .Values.migrationJob.backoffLimit }}