{
 "title": "Метрики API Методов",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Метод GET, ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(app_request_durations_histogram_seconds_bucket{action=\"GET-user_get\"}[$__rate_interval])))",
     "legendFormat": "0.5 Квантиль"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(app_request_durations_histogram_seconds_bucket{action=\"GET-user_get\"}[$__rate_interval])))",
     "legendFormat": "0.95 квантиль"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(app_request_durations_histogram_seconds_bucket{action=\"GET-user_get\"}[$__rate_interval])))",
     "legendFormat": "0.99 квантиль"
    }
   ]
  },
  {
   "title": "Метод PUT, ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(app_request_durations_histogram_seconds_bucket{action=\"PUT-user_update\"}[$__rate_interval])))",
     "legendFormat": "0.5 Квантиль"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(app_request_durations_histogram_seconds_bucket{action=\"PUT-user_update\"}[$__rate_interval])))",
     "legendFormat": "0.95 квантиль"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(app_request_durations_histogram_seconds_bucket{action=\"PUT-user_update\"}[$__rate_interval])))",
     "legendFormat": "0.99 квантиль"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "delta(app_http_requests_total{action=\"all\"}[$__interval])",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Errro 5XX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "idelta(app_http_5xx_responses_total{action=\"all\"}[$__interval])",
     "legendFormat": "pod: {{pod}}"
    }
   ]
  }
 ]
}