kind: ConfigMap
apiVersion: v1
metadata:
  name: app-env
data:
  .env.local: |
    APP_ENV=prod
    APP_SECRET=dd5d1f1d3126606ba31a2336c21b12c5
    DATABASE_URL="postgresql://postgres:postgres_pass@app-postgres-postgresql.m.svc.cluster.local:5432/service_1?serverVersion=16&charset=utf8"
