apiVersion: batch/v1
kind: Job
metadata:
  name: schema-migration-job
  annotations:
    "helm.sh/hook": post-upgrade,post-install
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    spec:
      containers:
        - name: schema-update
          image: kirshov/service-1
          command: [ '/bin/sh', '-c', '/app/bin/console do:mi:mi' ]
          volumeMounts:
            - name: app-env
              mountPath: '/app/.env.local'
              subPath: '.env.local'
      restartPolicy: Never
      volumes:
        - name: app-env
          configMap:
            name: app-env
  backoffLimit: 1
