appName: app

app:
  env: prod
  secret: dd5d1f1d3126606ba31a2336c21b12c5
  dbUrl: postgresql://postgres:postgres_pass@app-postgres-postgresql.default.svc.cluster.local:5432/users?serverVersion=16&charset=utf8

replicaCount: 1

serviceNginx:
  name: nginx
  image: nginx:latest
  volumeMounts:
    - name: app-nginx-config
      mountPath: '/etc/nginx/conf.d'
  portNumber: 80
  portName: nginx-port

serviceMainApp:
  image: kirshov/users-service:latest
  port:
    name: app-port
    containerPort: 8000
  volumeMounts:
    - name: app-env
      mountPath: '/app/.env.local'
      subPath: '.env.local'
    - name: cache-volume
      mountPath: '/app/var/'
  lifecycle:
    postStart:
      exec:
        command: [ '/bin/sh', '-c', 'chown -R www-data:www-data /app/var']

livenessProbe:
  httpGet:
    path: /health
    port: 80
  initialDelaySeconds: 3
  periodSeconds: 3

migrationJob:
  name: schema-migration-job
  containers:
    - name: schema-update
      image: kirshov/users-service:latest
      command: [ '/bin/sh', '-c', 'php /app/bin/console doctrine:migrations:migrate --no-interaction' ]
      volumeMounts:
        - name: app-env
          mountPath: '/app/.env.local'
          subPath: '.env.local'
  restartPolicy: Never
  volumes:
    - name: app-env
      configMap:
        name: app-env
  backoffLimit: 4

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

service:
  type: ClusterIP
  port: 80
  name: "service"
  portName: "web"

ingress:
  name: "ingress-nginx"
  enabled: false
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://service-auth.default.svc.cluster.local/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://service-auth.default.svc.cluster.local/signin"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-User,X-Email,X-UserId,X-First-Name,X-Last-Name"
  hosts:
    - host: arch.homework
      paths:
        - path: /
          pathType: Prefix
          serviceName: service
          servicePort: web
        #- path: /auth
        #  pathType: Prefix
        #  serviceName: service-auth
        #  servicePort: auth-web
  tls: []

metricsService:
  name: app-metrics
  path: "/metrics"
  portName: metrics
  port: 8090
  interval: 15s

prometheusService:
  name: prometheus
  nodePort: 30900
  port: 9090

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes:
  - name: app-nginx-config
    configMap:
      name: app-nginx-config
  - name: app-env
    configMap:
      name: app-env
  - name: cache-volume
    emptyDir: { }

secrets:
  postgresSecret: app-postgres-secret

configMaps:
  nginxConfigMap: app-nginx-config
  appConfigMap: app-env