artprima_prometheus_metrics:
  # namespace is used to prefix the prometheus metrics
  namespace: app

  # ignoring some routes in metrics
  ignored_routes: [ healthcheck, metrics, prometheus_bundle_prometheus ]

  # metrics backend
  storage:
    # DSN of the storage. All parsed values will override explicitly set parameters. Ex: redis://127.0.0.1?timeout=0.1
    url: ~

    # Known values: in_memory, apcu, apcng, redis
    type: apcu

    # Available parameters used by redis
    host: 127.0.0.1
    port: 6379
    timeout: 0.1
    read_timeout: 10
    persistent_connections: false
    password: ~
    database: 0 # Int value used by redis adapter
    prefix: metrics_   # String value used by redis and apcu

    # A variable parameter to define additionnal options as key / value.
    options:
      foo: bar

  # used to disable default application metrics
  disable_default_metrics: false

  # used to disable default metrics from promphp/prometheus_client_php
  disable_default_promphp_metrics: false

  # used to enable console metrics
  enable_console_metrics: false
